# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('reference', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
