site_name: scriptum-backend
site_description: TODO
repo_url: https://github.com/brian_petersen/scriptum-backend
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/brian_petersen">brian_petersen</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
